from enum import Enum

class SessionState(str, Enum):
    IDLE = "IDLE".lower()

    WAITING_GENERATE_TEXT = "WAITING_GENERATE_TEXT".lower()

    WAITING_DESIGN_PROMPT = "WAITING_DESIGN_PROMPT".lower()
    WAITING_DESIGN_TEXT = "WAITING_DESIGN_TEXT".lower()

    WAITING_CLONE_AUDIO = "WAITING_CLONE_AUDIO".lower()
    WAITING_CLONE_TEXT = "WAITING_CLONE_TEXT".lower()
    WAITING_CLONE_GENERATION_TEXT = "WAITING_CLONE_GENERATION_TEXT".lower()
